name: Generate Website Videos

on:
  repository_dispatch:
    types: [generate_websites]

permissions:
  contents: write
  actions: read

jobs:
  generate-videos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install system dependencies and Puppeteer requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ffmpeg \
          wget \
          ca-certificates \
          fonts-liberation \
          libappindicator3-1 \
          libasound2t64 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libc6 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgcc-s1 \
          libgdk-pixbuf2.0-0 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libstdc++6 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxss1 \
          libxtst6 \
          libxkbcommon0 \
          libdrm2 \
          libgbm1 \
          libpulse0 \
          libasound2-data \
          xdg-utils

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Node.js dependencies
      run: npm install

    - name: Process n8n website payload
      run: |
        echo "🔍 Processing website from n8n..."
        echo "Payload received: $PAYLOAD"
        
        # Ensure .github/scripts directory exists
        mkdir -p .github/scripts
        
        if [ -z "$PAYLOAD" ] || [ "$PAYLOAD" = "null" ]; then
          echo "❌ No payload provided from n8n"
          exit 1
        else
          echo "✅ Processing website data..."
          node .github/scripts/process-payload.js
        fi
        
        # Verify processing was successful
        if [ ! -f ".github/scripts/processing-results.json" ]; then
          echo "❌ Failed to process website data"
          exit 1
        fi
        
        echo "📋 Processing results:"
        cat .github/scripts/processing-results.json
      env:
        PAYLOAD: ${{ toJson(github.event.client_payload) }}
        NODE_ENV: production

    - name: Setup Xvfb for headless display
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 3

    - name: Create videos directory
      run: mkdir -p videos

    - name: Generate video using screenshot-based method
      run: |
        echo "🎬 Starting video generation for n8n website..."
        echo "Environment:"
        echo "  NODE_ENV: $NODE_ENV"
        echo "  PUPPETEER_EXECUTABLE_PATH: $PUPPETEER_EXECUTABLE_PATH"
        echo "  DISPLAY: $DISPLAY"
        
        # Check if we have website data to process
        if [ -f ".github/scripts/processing-results.json" ]; then
          WEBSITE_COUNT=$(jq length .github/scripts/processing-results.json)
          echo "📊 Found $WEBSITE_COUNT website to process"
          
          if [ "$WEBSITE_COUNT" -gt 0 ]; then
            echo "🚀 Running screenshot-based video generation..."
            node .github/scripts/generate-videos.js
            
            echo "📁 Checking generated videos..."
            if [ -d "videos" ]; then
              echo "Videos directory contents:"
              ls -la videos/
              VIDEO_COUNT=$(find videos -name "*.mp4" | wc -l)
              echo "Generated $VIDEO_COUNT video file(s)"
              if [ "$VIDEO_COUNT" -gt 0 ]; then
                echo "✅ Video generation successful!"
                find videos -name "*.mp4" -exec ls -lh {} \;
              else
                echo "❌ No video files found after generation"
                exit 1
              fi
            else
              echo "❌ Videos directory not found"
              exit 1
            fi
          else
            echo "❌ No website data to process"
            exit 1
          fi
        else
          echo "❌ No processing results found"
          exit 1
        fi
        
        echo "✅ Video generation completed successfully"
      timeout-minutes: 30
      env:
        NODE_ENV: production
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
        DISPLAY: :99

    - name: Create workflow summary
      run: |
        echo "# 🎬 Video Generation Summary" > workflow-summary.md
        echo "" >> workflow-summary.md
        echo "**Generated at:** $(date -u)" >> workflow-summary.md
        echo "**Triggered by:** n8n via repository_dispatch" >> workflow-summary.md
        echo "" >> workflow-summary.md
        
        if [ -d "videos" ]; then
          VIDEO_COUNT=$(find videos -name "*.mp4" | wc -l)
          echo "**Videos generated:** $VIDEO_COUNT" >> workflow-summary.md
          echo "" >> workflow-summary.md
          
          if [ "$VIDEO_COUNT" -gt 0 ]; then
            echo "## 📹 Generated Videos:" >> workflow-summary.md
            find videos -name "*.mp4" | while read video; do
              size=$(ls -lh "$video" | awk '{print $5}')
              filename=$(basename "$video")
              echo "- \`$filename\` ($size)" >> workflow-summary.md
            done
          fi
        else
          echo "**Videos generated:** 0" >> workflow-summary.md
        fi
        
        cat workflow-summary.md

    - name: Commit and push generated video
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Fetch latest changes
        echo "📡 Fetching latest changes..."
        git fetch origin main
        
        # Add generated files
        git add videos/ || true
        git add workflow-summary.md || true
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "ℹ️ No changes to commit"
          exit 0
        fi
        
        echo "💾 Committing generated video..."
        
        # Create commit
        git commit -m "🎥 Generated website video from n8n

        Generated at: $(date -u)
        Triggered by: n8n repository_dispatch
        Event type: generate_websites"
        
        # Push with retry logic
        MAX_RETRIES=3
        RETRY_COUNT=0
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          echo "📤 Push attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES..."
          
          if git push origin HEAD:main; then
            echo "✅ Successfully pushed video to repository!"
            break
          else
            echo "❌ Push failed, syncing with remote..."
            RETRY_COUNT=$((RETRY_COUNT + 1))
            
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              # Reset and pull latest changes
              git reset --soft HEAD~1
              git stash push -m "Generated video from n8n"
              git pull --rebase origin main
              git stash pop || true
              
              # Re-add and commit
              git add videos/ workflow-summary.md || true
              git commit -m "🎥 Generated website video from n8n

              Generated at: $(date -u)
              Triggered by: n8n repository_dispatch (retry $((RETRY_COUNT + 1)))" || {
                echo "No changes to re-commit after rebase"
                break
              }
              
              sleep 5
            else
              echo "❌ Max retries reached. Push failed."
              exit 1
            fi
          fi
        done

    - name: Upload video as artifact (backup)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: generated-video-${{ github.run_number }}
        path: |
          videos/
          workflow-summary.md
        retention-days: 30 